// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ScrapperData.Database.Models;

[Table("Colegiado")]
[Index("Identificacion", Name = "IX_Colegiado")]
[Index("NumeroCarne", Name = "IX_Colegiado_1")]
[Index("Nombre", Name = "IX_Colegiado_2")]
[Index("Estado", Name = "IX_Colegiado_3")]
[Index("Consultar", Name = "IX_Colegiado_4")]
[Index("EsNacional", Name = "IX_Colegiado_5")]
[Index("Identificacion", "ColegioId", Name = "IX_Colegiado_6")]
public partial class Colegiado
{
    [Key]
    public int Id { get; set; }

    public int? ColegioId { get; set; }

    public int? FotoColegiadoId { get; set; }

    public int CondicionColegiadoId { get; set; }

    [StringLength(100)]
    public string Identificacion { get; set; }

    [StringLength(200)]
    public string Nombre { get; set; }

    [StringLength(50)]
    public string NumeroCarne { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Telefono { get; set; }

    [StringLength(120)]
    public string CorreoElectronico { get; set; }

    public string Direccion { get; set; }

    public string LugarTrabajo { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string Especialidad { get; set; }

    public DateOnly? FechaIncorporacion { get; set; }

    [StringLength(70)]
    [Unicode(false)]
    public string TipoSuspencion { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? FechaReferencia { get; set; }

    [StringLength(250)]
    public string Fuente { get; set; }

    public bool Estado { get; set; }

    public bool Consultar { get; set; }

    public int? UniversidadId { get; set; }

    public bool? EsNacional { get; set; }

    public bool? Procesado { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string IdColegiado { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CitasInscripcion { get; set; }

    [ForeignKey("ColegioId")]
    [InverseProperty("Colegiados")]
    public virtual Colegio Colegio { get; set; }

    [ForeignKey("CondicionColegiadoId")]
    [InverseProperty("Colegiados")]
    public virtual EstadoColegiado CondicionColegiado { get; set; }

    [ForeignKey("FotoColegiadoId")]
    [InverseProperty("Colegiados")]
    public virtual FotoColegiado FotoColegiado { get; set; }
}