// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ScrapperData.Database.Models;

[Table("Colegio")]
public partial class Colegio
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(250)]
    public string Descripcion { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Profesion { get; set; }

    [StringLength(200)]
    public string Web { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime Fecha { get; set; }

    public bool Estado { get; set; }

    public bool Modulo { get; set; }

    [StringLength(50)]
    public string Titulo { get; set; }

    [InverseProperty("Colegio")]
    public virtual ICollection<Colegiado> Colegiados { get; set; } = new List<Colegiado>();
}