// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ScrapperData.Database.Models;

[Table("FotoColegiado")]
public partial class FotoColegiado
{
    [Key]
    public int Id { get; set; }

    public int? ColegiadoId { get; set; }

    [Column("FotoColegiado")]
    public byte[] FotoColegiado1 { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Fecha { get; set; }

    [InverseProperty("FotoColegiado")]
    public virtual ICollection<Colegiado> Colegiados { get; set; } = new List<Colegiado>();
}