// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using ScrapperData.Database.Models;

namespace ScrapperData.Database.Contexto;

public partial class ColegiosProfesionalesContext : DbContext
{
    public ColegiosProfesionalesContext()
    {
    }

    public ColegiosProfesionalesContext(DbContextOptions<ColegiosProfesionalesContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Colegiado> Colegiados { get; set; }

    public virtual DbSet<Colegio> Colegios { get; set; }

    public virtual DbSet<EstadoColegiado> EstadoColegiados { get; set; }

    public virtual DbSet<FotoColegiado> FotoColegiados { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=NAKAMA;Initial Catalog=ColegiosProfesionales;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Colegiado>(entity =>
        {
            entity.Property(e => e.Consultar).HasDefaultValue(true);
            entity.Property(e => e.Estado).HasDefaultValue(true);

            entity.HasOne(d => d.Colegio).WithMany(p => p.Colegiados).HasConstraintName("FK_Colegiado_Colegio");

            entity.HasOne(d => d.CondicionColegiado).WithMany(p => p.Colegiados)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Colegiado_EstadoColegiado");

            entity.HasOne(d => d.FotoColegiado).WithMany(p => p.Colegiados).HasConstraintName("FK_Colegiado_FotoColegiado");
        });

        modelBuilder.Entity<Colegio>(entity =>
        {
            entity.Property(e => e.Estado).HasDefaultValue(true);
            entity.Property(e => e.Fecha).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<EstadoColegiado>(entity =>
        {
            entity.Property(e => e.Descripcion).HasDefaultValueSql("((1))");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}